### ISSUE TITLE
Can the mnemonic module be used with non-crypto-currency keys?

### ISSUE THREAD

**Issue by NullVoxPopuli** [petejkim/wallet.ts#1]
I'm using NaCl for public key encryption, and it has keys of this length: 

`GtunIERnDlmmJWg7fLGb1cCqvSJfWX3ir68DhI2530A=` (base64)
```
1adba720 44670e59 
a625683b 7cb19bd5 
c0aabd22 5f597de2 
afaf0384 8db9df40
``` 
(hex)

basically just a 32 byte key

**Comment by petejkim** [comment]
Yep
